### ISSUE TITLE
Wildcards?

### ISSUE THREAD

**Issue by ghost** [bmv437/le-challenge-digitalocean#2]
Apparently greenlock supports wildcard certificates, but I've never been able to get them to work (https://github.com/Daplie/greenlock-express/issues/132). I know I need to use a DNS challenge, so I'm using this package to interface with DigitalOcean's DNS servers, and I see it creates a txt record at `_acme-challenge.[domain]`, and if I want to secure a subdomain, it makes one at `_acme-challenge.abc.[domain]`, and I am trying to secure wildcards, so I use this:
```
, approvedDomains: [domain, "*." + domain]
```
And I am curious if the issue is that a record cannot exist at `_acme-challenge.*.[domain]`.
Do you know how I would secure a wildcard subdomain with greenlock?

**Comment by coolaj86** [comment]
The record will be `_acme-challenge.example.com`. Wildcard and non-wildcard domains use the same domain since `*` is not a valid DNS identifier (or rather it has reserved special meaning).
